# Generated by Django 5.1.15 on 2026-10-04 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passphrase', models.CharField(max_length=128)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_pass_tokens', to=settings.AUTH_USER_MODEL)),
                ('loft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_tokens', to='core.loft')),
            ],
            options={
                'ordering': ['loft_id', '-valid_from', '-id'],
                'indexes': [models.Index(fields=['loft', 'revoked_at', 'valid_from', 'valid_until'], name='core_passto_loft_id_d09851_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_until__gt', models.F('valid_from'))), name='passtoken_until_after_from')],
            },
        ),
    ]
