# Generated by Django 5.1.15 on 2026-10-04 03:21

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.operations
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # GiST 标量列等值需要 btree_gist，排他约束依赖它
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.CreateModel(
            name='PassphraseToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaintext', models.CharField(max_length=120, verbose_name='口令明文')),
                ('valid_from', models.DateTimeField(verbose_name='生效时刻')),
                ('valid_until', models.DateTimeField(verbose_name='失效时刻')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='作废时刻')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_tokens', to=settings.AUTH_USER_MODEL, verbose_name='签发人')),
                ('loft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='core.loft')),
            ],
            options={
                'ordering': ['loft_id', '-valid_from', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_until__gt', models.F('valid_from'))), name='token_window_ordered'), django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('revoked_at__isnull', True)), expressions=[(models.F('loft'), '='), (models.Func(models.F('valid_from'), models.F('valid_until'), django.contrib.postgres.fields.ranges.RangeBoundary(), function='tstzrange'), '&&')], name='uniq_active_token_no_overlap', violation_error_message='同一帆布间未作废口令时段不得重叠')],
            },
        ),
    ]
